name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        default: '1.0.0-preview1'

env:
  Version: ${{ github.event.inputs.releaseVersion }}
  PackageVersion: ${{ github.event.inputs.releaseVersion }}

jobs:
  verify:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Test
      run: dotnet test --verbosity normal

  release_zip:
    needs: verify
    name: Release BaGet.zip to GitHub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: dotnet publish src/BaGet --configuration Release --output artifacts
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: BaGet
        path: artifacts
